name: 'Create Batch Endpoint'
description: 'Creates a batch endpoint in Azure Machine Learning'
inputs:
  endpoint_name:
    description: 'Name of the batch endpoint'
    required: true
  endpoint_description:
    description: 'Description of the batch endpoint'
    required: true
  auth_mode:
    description: 'Authentication mode for the endpoint'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install azure-ai-ml azure-identity
      shell: bash

    - name: Create batch endpoint
      env:
        AZURE_CLIENT_ID: ${{ fromJson(inputs.creds).clientId }}
        AZURE_TENANT_ID: ${{ fromJson(inputs.creds).tenantId }}
        AZURE_CLIENT_SECRET: ${{ fromJson(inputs.creds).clientSecret }}
      run: |
        python ${{ github.action_path }}/src/create_batch_endpoint.py \
          --endpoint_name "${{ inputs.endpoint_name }}" \
          --description "${{ inputs.endpoint_description }}" \
          --auth_mode "${{ inputs.auth_mode }}"
      shell: bash
