name: create-compute

on:
  workflow_call:
    inputs:
      cluster_name:
        required: true
        type: string
      size:
        required: true
        type: string
      min_instances:
        required: true
        type: number
      max_instances:
        required: true
        type: number
      cluster_tier:
        required: true
        type: string
    secrets:
      creds:
        required: true

jobs:
  create-compute:
    runs-on: ubuntu-latest
    steps:
      - name: Create compute
        env:
          AZURE_CLIENT_ID: ${{ fromJson(secrets.creds).clientId }}
          AZURE_TENANT_ID: ${{ fromJson(secrets.creds).tenantId }}
          AZURE_CLIENT_SECRET: ${{ fromJson(secrets.creds).clientSecret }}
        run: |
          python gha-py-sdk-v2-templates/python-sdk-v2-templates/create_compute.py \
            --cluster_name "${{ inputs.cluster_name }}" \
            --size "${{ inputs.size }}" \
            --min_instances ${{ inputs.min_instances }} \
            --max_instances ${{ inputs.max_instances }} \
            --cluster_tier "${{ inputs.cluster_tier }}"

