name: create-batch-deployment

on:
  workflow_call:
    inputs:
      deployment_name:
        required: true
        type: string
      deployment_description:
        required: true
        type: string
      endpoint_name:
        required: true
        type: string
      model_path:
        required: true
        type: string
      compute:
        required: true
        type: string
    secrets:
      creds:
        required: true

jobs:
  create-batch-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Create batch deployment
        env:
          AZURE_CLIENT_ID: ${{ fromJson(secrets.creds).clientId }}
          AZURE_TENANT_ID: ${{ fromJson(secrets.creds).tenantId }}
          AZURE_CLIENT_SECRET: ${{ fromJson(secrets.creds).clientSecret }}
        run: |
          python gha-py-sdk-v2-templates/python-sdk-v2-templates/create_batch_deployment.py \
            --deployment_name "${{ inputs.deployment_name }}" \
            --description "${{ inputs.deployment_description }}" \
            --endpoint_name "${{ inputs.endpoint_name }}" \
            --model_path "${{ inputs.model_path }}" \
            --compute "${{ inputs.compute }}"
