name: test-batch-endpoint

on:
  workflow_call:
    inputs:
      endpoint_name:
        required: true
        type: string
      sample_request:
        required: true
        type: string
      request_type:
        required: true
        type: string
    secrets:
      creds:
        required: true

jobs:
  test-batch-endpoint:
    runs-on: ubuntu-latest
    steps:
      - name: Test batch endpoint
        env:
          AZURE_CLIENT_ID: ${{ fromJson(secrets.creds).clientId }}
          AZURE_TENANT_ID: ${{ fromJson(secrets.creds).tenantId }}
          AZURE_CLIENT_SECRET: ${{ fromJson(secrets.creds).clientSecret }}
        run: |
          python gha-py-sdk-v2-templates/python-sdk-v2-templates/test_batch_endpoint.py \
            --endpoint_name "${{ inputs.endpoint_name }}" \
            --request_batch_file "${{ inputs.sample_request }}" \
            --request_type "${{ inputs.request_type }}"
