name: deploy-model-training-pipeline

on:
  workflow_dispatch:
jobs:
  set-env-branch:
    runs-on: ubuntu-latest
    outputs:
      config-file: ${{ steps.set-output-defaults.outputs.config-file }}
    steps:
      - id: set-prod-branch
        name: set-prod-branch
        if: ${{ github.ref == 'refs/heads/main'}}
        run: echo "config_env=infrastructure/env-variables/config-infra-prod.yml" >> $GITHUB_ENV;
      - id: set-stage-branch
        name: set-stage-branch
        if: ${{ github.ref == 'refs/heads/staging' }}
        run: echo "config_env=infrastructure/env-variables/config-infra-stage.yml" >> $GITHUB_ENV
      - id: set-dev-branch
        name: setdevbranch
        if: ${{ github.ref == 'refs/heads/develop'}}
        run: echo "config_env=infrastructure/env-variables/config-infra-dev.yml" >> $GITHUB_ENV;
        
      - id: set-output-defaults
        name: set-output-defaults
        run: |
          echo "config-file=$config_env" >> $GITHUB_OUTPUT;
  get-config:
    needs: set-env-branch
    uses: gha-py-sdk-v2-templates/read_yaml_action
    with:
      file_name: ${{ needs.set-env-branch.outputs.config-file}}
  register-environment:
    needs: get-config
    uses: gha-py-sdk-v2-templates/register-environment.yml
    with:
      resource_group: ${{ needs.get-config.outputs.resource_group }}
      workspace_name: ${{ needs.get-config.outputs.aml_workspace }}
      environment_file: amlws-assets/environment/automl-env.yml
      conda_file: amlws-assets/environment/automl-conda.yml
    secrets:
      creds: ${{secrets.AZURE_CREDENTIALS}}
  register-dataset:
    needs: get-config
    uses: gha-py-sdk-v2-templates/register-dataset.yml
    with:
      resource_group: ${{ needs.get-config.outputs.resource_group }}
      workspace_name: ${{ needs.get-config.outputs.aml_workspace }}
      name: data
      data_file: amlws-assets/data/data.yml
    secrets:
      creds: ${{secrets.AZURE_CREDENTIALS}}
  create-compute:
    needs: [get-config]
    uses: gha-py-sdk-v2-templates/create-compute.yml
    with:
      cluster_name: cpu-cluster
      size: Standard_DS3_v2
      min_instances: 0
      max_instances: 4
      cluster_tier: low_priority
      resource_group: ${{ needs.get-config.outputs.resource_group }}
      workspace_name: ${{ needs.get-config.outputs.aml_workspace }}
    secrets:
      creds: ${{secrets.AZURE_CREDENTIALS}}
  run-model-training-pipeline:
    needs: [get-config, register-environment, register-dataset, create-compute]
    uses: gha-py-sdk-v2-templates/run-pipeline.yml
    with:
      experiment_name: "dev-taxi-fare-training"
      data_name: "data"
      environment_name: "automl-env"
      compute_name: "cpu-cluster"
      enable_monitoring: ${{ needs.get-config.outputs.enable_monitoring }}
      table_name: "taximonitoring"
      pipeline_path: "amlws-assets/pipelinejobs/dev-train.py"
    secrets:
      creds: ${{secrets.AZURE_CREDENTIALS}}
