name: 'Create Batch Deployment'
description: 'Creates a batch deployment in Azure Machine Learning'
inputs:
  deployment_name:
    description: 'Name of the batch deployment'
    required: true
  deployment_description:
    description: 'Description of the batch deployment'
    required: true
  endpoint_name:
    description: 'Name of the batch endpoint'
    required: true
  model_path:
    description: 'Path to the model or AML model reference'
    required: true
  compute:
    description: 'Name of the compute cluster'
    required: true
  instance_count:
    description: 'Number of instances to provision for job'
    default: '2'
  max_concurrency_per_instance:
    description: 'Maximum number of concurrent jobs per instance'
    default: '4'
  mini_batch_size:
    description: 'The number of examples to score per job'
    default: '32'
  output_file_name:
    description: 'Output file name'
    default: 'predictions.csv'
  azure_credentials:
    description: 'Azure credentials'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install azure-ai-ml azure-identity
      shell: bash

    - name: Create batch deployment
      env:
        AZURE_CREDENTIALS: ${{ inputs.azure_credentials }}
      run: |
        python ${{ github.action_path }}/create_batch_deployment.py \
          --deployment_name "${{ inputs.deployment_name }}" \
          --description "${{ inputs.deployment_description }}" \
          --endpoint_name "${{ inputs.endpoint_name }}" \
          --model_path "${{ inputs.model_path }}" \
          --compute "${{ inputs.compute }}" \
          --instance_count "${{ inputs.instance_count }}" \
          --max_concurrency_per_instance "${{ inputs.max_concurrency_per_instance }}" \
          --mini_batch_size "${{ inputs.mini_batch_size }}" \
          --output_file_name "${{ inputs.output_file_name }}"
      shell: bash
