name: create-compute-instance

on:
  workflow_call:
    inputs:
      instance_name:
        required: true
        type: string
      size:
        required: true
        type: string
      location:
        required: true
        type: string
      description:
        required: true
        type: string
      identity_type:
        required: true
        type: string
      user_assigned_identity:
        required: false
        type: string
        default: " "
    secrets:
      creds:
        required: true

jobs:
  create-compute-instance:
    runs-on: ubuntu-latest
    steps:
      - name: Create compute instance
        env:
          AZURE_CLIENT_ID: ${{ fromJson(secrets.creds).clientId }}
          AZURE_TENANT_ID: ${{ fromJson(secrets.creds).tenantId }}
          AZURE_CLIENT_SECRET: ${{ fromJson(secrets.creds).clientSecret }}
        run: |
          python src/create_compute_instance.py \
            --instance_name "${{ inputs.instance_name }}" \
            --size "${{ inputs.size }}" \
            --location "${{ inputs.location }}" \
            --description "${{ inputs.description }}" \
            --identity_type "${{ inputs.identity_type }}" \
            --user_assigned_identity "${{ inputs.user_assigned_identity }}"
