name: 'Register Environment'
description: 'Registers an environment in Azure Machine Learning'
inputs:
  environment_name:
    description: 'Name of the environment'
    required: true
  environment_description:
    description: 'Description of the environment'
    required: true
  environment_path:
    description: 'Path to the environment file'
    required: true
  build_type:
    description: 'Build type for the environment (docker or conda)'
    required: true
    default: 'conda'
  base_image:
    description: 'Base image for the environment'
    default: 'mcr.microsoft.com/azureml/openmpi3.1.2-ubuntu18.04'
  azure_credentials:
    description: 'Azure credentials'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install azure-ai-ml azure-identity
      shell: bash

    - name: Register environment
      env:
        AZURE_CREDENTIALS: ${{ inputs.azure_credentials }}
      run: |
        python src/register_environment.py \
          --environment_name "${{ inputs.environment_name }}" \
          --description "${{ inputs.environment_description }}" \
          --env_path "${{ inputs.environment_path }}" \
          --build_type "${{ inputs.build_type }}" \
          --base_image "${{ inputs.base_image }}"
      shell: bash
