# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

# Prod environment
variables:
  # Global
  ap_vm_image: ubuntu-20.04

  namespace: ghapysdk #Note: A namespace with many characters will cause storage account creation to fail due to storage account names having a limit of 24 characters.
  postfix: 0001
  location: uksouth
  environment: stage
  enable_aml_computecluster: true
  enable_monitoring: false
  environment_name: automl
  environment_description: automl for staging test data
  environment_path: amlws-assets/environment/automl-conda.yml
  build_type: conda
  pipeline_file: amlws-assets/pipelinejobs/dev-train.py
  virtual_environment: azure
  modelname: automl
  data_name: stage
  data_path: amlws-assets/data/stage
  data_type: mltable
  data_description: staging test data
  subscription_id: 1c81448f-a844-4192-b988-9f247a70c83f

  # DO NOT TOUCH

  # For pipeline reference
  resource_group: rg-$(namespace)-$(postfix)$(environment)
  aml_workspace: mlw-$(namespace)-$(postfix)$(environment)
  application_insights: mlw-$(namespace)-$(postfix)$(environment)
  key_vault: kv-$(namespace)-$(postfix)$(environment)
  container_registry: cr$(namespace)$(postfix)$(environment)
  storage_account: st$(namespace)$(postfix)$(environment)

  # For terraform reference
  terraform_version: 1.3.6
  terraform_workingdir: infrastructure
  terraform_st_location: $(location)
  terraform_st_resource_group: rg-$(namespace)-$(postfix)$(environment)-tf
  terraform_st_storage_account: st$(namespace)$(postfix)$(environment)tf
  terraform_st_container_name: default
  terraform_st_key: mlops-tab
